#ifndef _SEA_BATTLE_COMMON_CONSTANTS_FIELDORIENTATION_HPP
#define _SEA_BATTLE_COMMON_CONSTANTS_FIELDORIENTATION_HPP

namespace Enum{

struct FieldOrientation {

    enum type {
        RIGHT = 0,
        LEFT = 1
    };
};
}


#endif //_SEA_BATTLE_COMMON_CONSTANTS_FIELDORIENTATION_HPP